/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * rg-dez-backend
 * OpenAPI spec version: 0.8.0
 */
import { apiClient } from "../lib/apiClient";
export type Def0Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Bad request, input malformed.
 */
export interface Def0 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def0Internal;
}

export type Def1Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Unauthorized
 */
export interface Def1 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def1Internal;
}

export type Def2Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Forbidden
 */
export interface Def2 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def2Internal;
}

export type Def3Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Not found
 */
export interface Def3 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def3Internal;
}

export type Def4Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Method not allowed
 */
export interface Def4 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def4Internal;
}

export type Def5Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Internal server error
 */
export interface Def5 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def5Internal;
}

/**
 * Health Check Succeeded
 */
export type GetHealth200 = {
  status?: string;
};

/**
 * Error Performing Health Check
 */
export type GetHealth500 = {
  /** Error message for failure during health check */
  message?: string;
  /** Code representing the error. Always matches the HTTP response code. */
  statusCode?: number;
};

/**
 * Health Check Failed
 */
export type GetHealth503 = {
  /** Error code associated with the failing check */
  code?: string;
  /** Error thrown during health check */
  error?: string;
  /** Error message to explain health check failure */
  message?: string;
  /** Code representing the error. Always matches the HTTP response code. */
  statusCode?: number;
};

export type GetApiAdminAuthVerify200AccessTokenRealmAccess = {
  roles: string[];
};

export type GetApiAdminAuthVerify200AccessTokenResourceAccess = {
  [key: string]: {
    roles: string[];
  };
};

export type GetApiAdminAuthVerify200AccessToken = {
  scope?: string;
  client_id?: string;
  username?: string;
  token_type?: string;
  exp?: number;
  iat?: number;
  nbf?: number;
  sub?: string;
  aud?: string | string[];
  iss?: string;
  jti?: string;
  realm_access?: GetApiAdminAuthVerify200AccessTokenRealmAccess;
  resource_access?: GetApiAdminAuthVerify200AccessTokenResourceAccess;
  name?: string;
  given_name?: string;
  family_name?: string;
  email_verified?: boolean;
  preferred_username?: string;
  email?: string;
  [key: string]: unknown;
};

export type GetApiAdminAuthVerify200 = {
  accessToken: GetApiAdminAuthVerify200AccessToken;
};

export type GetApiAdminConfig200ConfigsItem = {
  versionName: string;
  calculationConfig: string;
  subsidies: string[];
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiAdminConfig200 = {
  configs: GetApiAdminConfig200ConfigsItem[];
};

export type PostApiAdminConfigBody = {
  /** @minLength 1 */
  versionName: string;
  calculationConfig: string;
  subsidies: string[];
};

export type PostApiAdminConfig200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string[];
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiAdminConfigVersionName200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string[];
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type DeleteApiAdminConfigVersionName200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string[];
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiPublicConfigActive200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string[];
  publishedAt: unknown;
};

export type GetApiPublicMapResources200 = {
  /** @minLength 1 */
  terrainBaseUrl: string;
  /** @minLength 1 */
  tilesBaseUrl: string;
  /** @minLength 1 */
  addressDatabaseUrl: string;
};

export type PatchApiAdminConfigVersionNameActivate200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string[];
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiAdminFeedbackParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minLength 1
   */
  category?: string;
  sortBy?: (typeof GetApiAdminFeedbackSortBy)[keyof typeof GetApiAdminFeedbackSortBy];
  sortOrder?: (typeof GetApiAdminFeedbackSortOrder)[keyof typeof GetApiAdminFeedbackSortOrder];
};

export const GetApiAdminFeedbackSortBy = {
  createdAt: "createdAt",
  category: "category",
} as const;
export const GetApiAdminFeedbackSortOrder = {
  asc: "asc",
  desc: "desc",
} as const;
export const GetApiAdminFeedback200DataItemCategory = {
  bug: "bug",
  feedback: "feedback",
  suggestion: "suggestion",
} as const;
export type GetApiAdminFeedback200DataItem = {
  id: string;
  category: (typeof GetApiAdminFeedback200DataItemCategory)[keyof typeof GetApiAdminFeedback200DataItemCategory];
  message: string;
  emailAddress: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetApiAdminFeedback200 = {
  data: GetApiAdminFeedback200DataItem[];
  total: number;
};

export const GetApiAdminFeedbackFeedbackId200Category = {
  bug: "bug",
  feedback: "feedback",
  suggestion: "suggestion",
} as const;
export type GetApiAdminFeedbackFeedbackId200 = {
  id: string;
  category: (typeof GetApiAdminFeedbackFeedbackId200Category)[keyof typeof GetApiAdminFeedbackFeedbackId200Category];
  message: string;
  emailAddress: string | null;
  createdAt: string;
  updatedAt: string;
};

export const PostApiPublicFeedbackBodyCategory = {
  bug: "bug",
  feedback: "feedback",
  suggestion: "suggestion",
} as const;
export type PostApiPublicFeedbackBody = {
  category: (typeof PostApiPublicFeedbackBodyCategory)[keyof typeof PostApiPublicFeedbackBodyCategory];
  message: string;
  emailAddress?: string;
};

export type GetApiAdminSubmissionsParams = {
  managerId?: string;
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  status?: (typeof GetApiAdminSubmissionsStatus)[keyof typeof GetApiAdminSubmissionsStatus];
  sortBy?: (typeof GetApiAdminSubmissionsSortBy)[keyof typeof GetApiAdminSubmissionsSortBy];
};

export const GetApiAdminSubmissionsStatus = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export const GetApiAdminSubmissionsSortBy = {
  status: "status",
  submitted: "submitted",
} as const;
export const GetApiAdminSubmissions200DataItemSubmissionsItemStatus = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export type GetApiAdminSubmissions200DataItemSubmissionsItem = {
  id: string;
  status: (typeof GetApiAdminSubmissions200DataItemSubmissionsItemStatus)[keyof typeof GetApiAdminSubmissions200DataItemSubmissionsItemStatus];
  assignedToId: string | null;
  createdAt: string;
};

export type GetApiAdminSubmissions200DataItem = {
  buildingId: string;
  address: string;
  longitude: number;
  latitude: number;
  submissionCount: number;
  submissions: GetApiAdminSubmissions200DataItemSubmissionsItem[];
};

export type GetApiAdminSubmissions200 = {
  data: GetApiAdminSubmissions200DataItem[];
  total: number;
};

export const GetApiAdminSubmissionsSubmissionId200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export type GetApiAdminSubmissionsSubmissionId200AssignedTo = {
  id: string;
  email: string;
  given_name: string | null;
  family_name: string | null;
} | null;

export type GetApiAdminSubmissionsSubmissionId200NgsiData = {
  [key: string]: unknown;
};

export type GetApiAdminSubmissionsSubmissionId200Raw = {
  [key: string]: unknown;
};

export type GetApiAdminSubmissionsSubmissionId200UsedConfig = {
  id: string;
  versionName: string;
} | null;

export const GetApiAdminSubmissionsSubmissionId200HistoryItemFrom = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export const GetApiAdminSubmissionsSubmissionId200HistoryItemTo = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export type GetApiAdminSubmissionsSubmissionId200HistoryItemBy = {
  id: string;
  email: string;
  given_name: string | null;
  family_name: string | null;
};

export type GetApiAdminSubmissionsSubmissionId200HistoryItem = {
  id: string;
  from: (typeof GetApiAdminSubmissionsSubmissionId200HistoryItemFrom)[keyof typeof GetApiAdminSubmissionsSubmissionId200HistoryItemFrom];
  to: (typeof GetApiAdminSubmissionsSubmissionId200HistoryItemTo)[keyof typeof GetApiAdminSubmissionsSubmissionId200HistoryItemTo];
  by: GetApiAdminSubmissionsSubmissionId200HistoryItemBy;
  comment: string | null;
  relatedSubmissionId: string | null;
  createdAt: string;
};

export type GetApiAdminSubmissionsSubmissionId200 = {
  id: string;
  status: (typeof GetApiAdminSubmissionsSubmissionId200Status)[keyof typeof GetApiAdminSubmissionsSubmissionId200Status];
  buildingId: string;
  address: string;
  longitude: number;
  latitude: number;
  otherSubmissionIds: string[];
  currentAcceptedSubmissionId: string | null;
  allSubmissionsDeclined: boolean;
  /** @minimum 1 */
  submissionCount: number;
  assignedTo: GetApiAdminSubmissionsSubmissionId200AssignedTo;
  assignedAt: string | null;
  ngsiData: GetApiAdminSubmissionsSubmissionId200NgsiData;
  raw: GetApiAdminSubmissionsSubmissionId200Raw;
  usedConfig: GetApiAdminSubmissionsSubmissionId200UsedConfig;
  history: GetApiAdminSubmissionsSubmissionId200HistoryItem[];
  createdAt: string;
  updatedAt: string;
};

export type DeleteApiAdminSubmissionsSubmissionId200ReceiptVersion =
  (typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptVersion)[keyof typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptVersion];

export const DeleteApiAdminSubmissionsSubmissionId200ReceiptVersion = {
  NUMBER_1: 1,
} as const;

export const DeleteApiAdminSubmissionsSubmissionId200ReceiptAction = {
  SUBMISSION_DELETE: "SUBMISSION_DELETE",
  BUILDING_SUBMISSIONS_DELETE: "BUILDING_SUBMISSIONS_DELETE",
} as const;
export const DeleteApiAdminSubmissionsSubmissionId200ReceiptActorType = {
  ADMIN: "ADMIN",
  PUBLIC_CAPABILITY: "PUBLIC_CAPABILITY",
} as const;
export const DeleteApiAdminSubmissionsSubmissionId200ReceiptTargetType = {
  SUBMISSION: "SUBMISSION",
  BUILDING: "BUILDING",
} as const;
export type DeleteApiAdminSubmissionsSubmissionId200Receipt = {
  version: DeleteApiAdminSubmissionsSubmissionId200ReceiptVersion;
  auditEventId: string;
  deletedAt: string;
  action: (typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptAction)[keyof typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptAction];
  actorType: (typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptActorType)[keyof typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptActorType];
  targetType: (typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptTargetType)[keyof typeof DeleteApiAdminSubmissionsSubmissionId200ReceiptTargetType];
  targetId: string;
  /** @minimum 1 */
  deletedCount: number;
  /**
   * @minLength 43
   * @maxLength 43
   */
  verificationSecret: string;
};

export type DeleteApiAdminSubmissionsSubmissionId200 = {
  id: string;
  receipt: DeleteApiAdminSubmissionsSubmissionId200Receipt;
};

export type DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptVersion =
  (typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptVersion)[keyof typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptVersion];

export const DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptVersion = {
  NUMBER_1: 1,
} as const;

export const DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptAction = {
  SUBMISSION_DELETE: "SUBMISSION_DELETE",
  BUILDING_SUBMISSIONS_DELETE: "BUILDING_SUBMISSIONS_DELETE",
} as const;
export const DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptActorType = {
  ADMIN: "ADMIN",
  PUBLIC_CAPABILITY: "PUBLIC_CAPABILITY",
} as const;
export const DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptTargetType = {
  SUBMISSION: "SUBMISSION",
  BUILDING: "BUILDING",
} as const;
export type DeleteApiAdminSubmissionsBuildingBuildingId200Receipt = {
  version: DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptVersion;
  auditEventId: string;
  deletedAt: string;
  action: (typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptAction)[keyof typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptAction];
  actorType: (typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptActorType)[keyof typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptActorType];
  targetType: (typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptTargetType)[keyof typeof DeleteApiAdminSubmissionsBuildingBuildingId200ReceiptTargetType];
  targetId: string;
  /** @minimum 1 */
  deletedCount: number;
  /**
   * @minLength 43
   * @maxLength 43
   */
  verificationSecret: string;
};

export type DeleteApiAdminSubmissionsBuildingBuildingId200 = {
  buildingId: string;
  /** @minimum 1 */
  deletedCount: number;
  receipt: DeleteApiAdminSubmissionsBuildingBuildingId200Receipt;
};

export const DeleteApiAdminSubmissionsSubmissionIdAssignment200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export type DeleteApiAdminSubmissionsSubmissionIdAssignment200 = {
  id: string;
  status: (typeof DeleteApiAdminSubmissionsSubmissionIdAssignment200Status)[keyof typeof DeleteApiAdminSubmissionsSubmissionIdAssignment200Status];
  assignedToId: string | null;
  assignedAt: string | null;
};

export type PatchApiAdminSubmissionsSubmissionIdAssignmentBody = {
  userId?: string;
};

export const PatchApiAdminSubmissionsSubmissionIdAssignment200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export type PatchApiAdminSubmissionsSubmissionIdAssignment200 = {
  id: string;
  status: (typeof PatchApiAdminSubmissionsSubmissionIdAssignment200Status)[keyof typeof PatchApiAdminSubmissionsSubmissionIdAssignment200Status];
  assignedToId: string | null;
  assignedAt: string | null;
};

export type PostApiAdminSubmissionsSubmissionIdAcceptBody = {
  /** @maxLength 4000 */
  comment?: string;
};

export type PostApiAdminSubmissionsSubmissionIdAccept200 = {
  id: string;
  status: "NEW" | "ASSIGNED" | "ACCEPTED" | "DECLINED" | "SUPERSEDED";
  assignedToId: string | null;
  assignedAt: string | null;
} & {
  supersededSubmissionIds: string[];
  declinedSubmissionIds: string[];
};

export type PostApiAdminSubmissionsSubmissionIdDeclineBody = {
  /** @maxLength 4000 */
  comment?: string;
};

export const PostApiAdminSubmissionsSubmissionIdDecline200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  SUPERSEDED: "SUPERSEDED",
} as const;
export type PostApiAdminSubmissionsSubmissionIdDecline200 = {
  id: string;
  status: (typeof PostApiAdminSubmissionsSubmissionIdDecline200Status)[keyof typeof PostApiAdminSubmissionsSubmissionIdDecline200Status];
  assignedToId: string | null;
  assignedAt: string | null;
};

export type PostApiPublicSubmissionsBody = {
  input: unknown;
  configName?: string;
  buildingId: string;
  address: string;
  longitude: number;
  latitude: number;
};

export type PostApiPublicSubmissions200 = {
  deletionToken: string;
};

export type PostApiPublicSubmissionsDeletionReceiptsVerifyBodyVersion =
  (typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyVersion)[keyof typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyVersion];

export const PostApiPublicSubmissionsDeletionReceiptsVerifyBodyVersion = {
  NUMBER_1: 1,
} as const;

export const PostApiPublicSubmissionsDeletionReceiptsVerifyBodyAction = {
  SUBMISSION_DELETE: "SUBMISSION_DELETE",
  BUILDING_SUBMISSIONS_DELETE: "BUILDING_SUBMISSIONS_DELETE",
} as const;
export const PostApiPublicSubmissionsDeletionReceiptsVerifyBodyActorType = {
  ADMIN: "ADMIN",
  PUBLIC_CAPABILITY: "PUBLIC_CAPABILITY",
} as const;
export const PostApiPublicSubmissionsDeletionReceiptsVerifyBodyTargetType = {
  SUBMISSION: "SUBMISSION",
  BUILDING: "BUILDING",
} as const;
export type PostApiPublicSubmissionsDeletionReceiptsVerifyBody = {
  version: PostApiPublicSubmissionsDeletionReceiptsVerifyBodyVersion;
  auditEventId: string;
  deletedAt: string;
  action: (typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyAction)[keyof typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyAction];
  actorType: (typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyActorType)[keyof typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyActorType];
  targetType: (typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyTargetType)[keyof typeof PostApiPublicSubmissionsDeletionReceiptsVerifyBodyTargetType];
  targetId: string;
  /** @minimum 1 */
  deletedCount: number;
  /**
   * @minLength 43
   * @maxLength 43
   */
  verificationSecret: string;
};

export type PostApiPublicSubmissionsDeletionReceiptsVerify200 = {
  valid: boolean;
};

export type GetApiPublicSubmissionsDeletionTokenStatus200 = {
  available: boolean;
};

export type GetApiPublicSubmissionsDeletionTokenDownload200Raw = {
  [key: string]: unknown;
};

export type GetApiPublicSubmissionsDeletionTokenDownload200NgsiData = {
  [key: string]: unknown;
};

export type GetApiPublicSubmissionsDeletionTokenDownload200 = {
  id: string;
  buildingId: string;
  address: string;
  longitude: number;
  latitude: number;
  configName?: string;
  createdAt: string;
  raw: GetApiPublicSubmissionsDeletionTokenDownload200Raw;
  ngsiData: GetApiPublicSubmissionsDeletionTokenDownload200NgsiData;
  deletionLink: string;
};

export type DeleteApiPublicSubmissionsDeletionToken200ReceiptVersion =
  (typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptVersion)[keyof typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptVersion];

export const DeleteApiPublicSubmissionsDeletionToken200ReceiptVersion = {
  NUMBER_1: 1,
} as const;

export const DeleteApiPublicSubmissionsDeletionToken200ReceiptAction = {
  SUBMISSION_DELETE: "SUBMISSION_DELETE",
  BUILDING_SUBMISSIONS_DELETE: "BUILDING_SUBMISSIONS_DELETE",
} as const;
export const DeleteApiPublicSubmissionsDeletionToken200ReceiptActorType = {
  ADMIN: "ADMIN",
  PUBLIC_CAPABILITY: "PUBLIC_CAPABILITY",
} as const;
export const DeleteApiPublicSubmissionsDeletionToken200ReceiptTargetType = {
  SUBMISSION: "SUBMISSION",
  BUILDING: "BUILDING",
} as const;
export type DeleteApiPublicSubmissionsDeletionToken200Receipt = {
  version: DeleteApiPublicSubmissionsDeletionToken200ReceiptVersion;
  auditEventId: string;
  deletedAt: string;
  action: (typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptAction)[keyof typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptAction];
  actorType: (typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptActorType)[keyof typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptActorType];
  targetType: (typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptTargetType)[keyof typeof DeleteApiPublicSubmissionsDeletionToken200ReceiptTargetType];
  targetId: string;
  /** @minimum 1 */
  deletedCount: number;
  /**
   * @minLength 43
   * @maxLength 43
   */
  verificationSecret: string;
};

export type DeleteApiPublicSubmissionsDeletionToken200 = {
  success: boolean;
  receipt: DeleteApiPublicSubmissionsDeletionToken200Receipt;
};

export const getGetHealthUrl = () => {
  return `/health`;
};

export const getHealth = async (
  options?: RequestInit,
): Promise<GetHealth200> => {
  return apiClient<GetHealth200>(getGetHealthUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetApiAdminAuthVerifyUrl = () => {
  return `/api/admin/auth/verify`;
};

export const getApiAdminAuthVerify = async (
  options?: RequestInit,
): Promise<GetApiAdminAuthVerify200> => {
  return apiClient<GetApiAdminAuthVerify200>(getGetApiAdminAuthVerifyUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetApiAdminConfigUrl = () => {
  return `/api/admin/config`;
};

export const getApiAdminConfig = async (
  options?: RequestInit,
): Promise<GetApiAdminConfig200> => {
  return apiClient<GetApiAdminConfig200>(getGetApiAdminConfigUrl(), {
    ...options,
    method: "GET",
  });
};

export const getPostApiAdminConfigUrl = () => {
  return `/api/admin/config`;
};

export const postApiAdminConfig = async (
  postApiAdminConfigBody: PostApiAdminConfigBody,
  options?: RequestInit,
): Promise<PostApiAdminConfig200> => {
  return apiClient<PostApiAdminConfig200>(getPostApiAdminConfigUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiAdminConfigBody),
  });
};

export const getGetApiAdminConfigVersionNameUrl = (versionName: string) => {
  return `/api/admin/config/${versionName}`;
};

export const getApiAdminConfigVersionName = async (
  versionName: string,
  options?: RequestInit,
): Promise<GetApiAdminConfigVersionName200> => {
  return apiClient<GetApiAdminConfigVersionName200>(
    getGetApiAdminConfigVersionNameUrl(versionName),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDeleteApiAdminConfigVersionNameUrl = (versionName: string) => {
  return `/api/admin/config/${versionName}`;
};

export const deleteApiAdminConfigVersionName = async (
  versionName: string,
  options?: RequestInit,
): Promise<DeleteApiAdminConfigVersionName200> => {
  return apiClient<DeleteApiAdminConfigVersionName200>(
    getDeleteApiAdminConfigVersionNameUrl(versionName),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getGetApiPublicConfigActiveUrl = () => {
  return `/api/public/config/active`;
};

export const getApiPublicConfigActive = async (
  options?: RequestInit,
): Promise<GetApiPublicConfigActive200> => {
  return apiClient<GetApiPublicConfigActive200>(
    getGetApiPublicConfigActiveUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPublicMapResourcesUrl = () => {
  return `/api/public/map-resources`;
};

export const getApiPublicMapResources = async (
  options?: RequestInit,
): Promise<GetApiPublicMapResources200> => {
  return apiClient<GetApiPublicMapResources200>(
    getGetApiPublicMapResourcesUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getPatchApiAdminConfigVersionNameActivateUrl = (
  versionName: string,
) => {
  return `/api/admin/config/${versionName}/activate`;
};

export const patchApiAdminConfigVersionNameActivate = async (
  versionName: string,
  options?: RequestInit,
): Promise<PatchApiAdminConfigVersionNameActivate200> => {
  return apiClient<PatchApiAdminConfigVersionNameActivate200>(
    getPatchApiAdminConfigVersionNameActivateUrl(versionName),
    {
      ...options,
      method: "PATCH",
    },
  );
};

export const getGetApiAdminFeedbackUrl = (
  params?: GetApiAdminFeedbackParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/feedback?${stringifiedParams}`
    : `/api/admin/feedback`;
};

export const getApiAdminFeedback = async (
  params?: GetApiAdminFeedbackParams,
  options?: RequestInit,
): Promise<GetApiAdminFeedback200> => {
  return apiClient<GetApiAdminFeedback200>(getGetApiAdminFeedbackUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetApiAdminFeedbackFeedbackIdUrl = (feedbackId: string) => {
  return `/api/admin/feedback/${feedbackId}`;
};

export const getApiAdminFeedbackFeedbackId = async (
  feedbackId: string,
  options?: RequestInit,
): Promise<GetApiAdminFeedbackFeedbackId200> => {
  return apiClient<GetApiAdminFeedbackFeedbackId200>(
    getGetApiAdminFeedbackFeedbackIdUrl(feedbackId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDeleteApiAdminFeedbackFeedbackIdUrl = (feedbackId: string) => {
  return `/api/admin/feedback/${feedbackId}`;
};

export const deleteApiAdminFeedbackFeedbackId = async (
  feedbackId: string,
  options?: RequestInit,
): Promise<unknown> => {
  return apiClient<unknown>(
    getDeleteApiAdminFeedbackFeedbackIdUrl(feedbackId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getPostApiPublicFeedbackUrl = () => {
  return `/api/public/feedback`;
};

export const postApiPublicFeedback = async (
  postApiPublicFeedbackBody: PostApiPublicFeedbackBody,
  options?: RequestInit,
): Promise<void> => {
  return apiClient<void>(getPostApiPublicFeedbackUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiPublicFeedbackBody),
  });
};

export const getGetApiAdminSubmissionsUrl = (
  params?: GetApiAdminSubmissionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/submissions?${stringifiedParams}`
    : `/api/admin/submissions`;
};

export const getApiAdminSubmissions = async (
  params?: GetApiAdminSubmissionsParams,
  options?: RequestInit,
): Promise<GetApiAdminSubmissions200> => {
  return apiClient<GetApiAdminSubmissions200>(
    getGetApiAdminSubmissionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiAdminSubmissionsSubmissionIdUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}`;
};

export const getApiAdminSubmissionsSubmissionId = async (
  submissionId: string,
  options?: RequestInit,
): Promise<GetApiAdminSubmissionsSubmissionId200> => {
  return apiClient<GetApiAdminSubmissionsSubmissionId200>(
    getGetApiAdminSubmissionsSubmissionIdUrl(submissionId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDeleteApiAdminSubmissionsSubmissionIdUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}`;
};

export const deleteApiAdminSubmissionsSubmissionId = async (
  submissionId: string,
  options?: RequestInit,
): Promise<DeleteApiAdminSubmissionsSubmissionId200> => {
  return apiClient<DeleteApiAdminSubmissionsSubmissionId200>(
    getDeleteApiAdminSubmissionsSubmissionIdUrl(submissionId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteApiAdminSubmissionsBuildingBuildingIdUrl = (
  buildingId: string,
) => {
  return `/api/admin/submissions/building/${buildingId}`;
};

export const deleteApiAdminSubmissionsBuildingBuildingId = async (
  buildingId: string,
  options?: RequestInit,
): Promise<DeleteApiAdminSubmissionsBuildingBuildingId200> => {
  return apiClient<DeleteApiAdminSubmissionsBuildingBuildingId200>(
    getDeleteApiAdminSubmissionsBuildingBuildingIdUrl(buildingId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteApiAdminSubmissionsSubmissionIdAssignmentUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/assignment`;
};

export const deleteApiAdminSubmissionsSubmissionIdAssignment = async (
  submissionId: string,
  options?: RequestInit,
): Promise<DeleteApiAdminSubmissionsSubmissionIdAssignment200> => {
  return apiClient<DeleteApiAdminSubmissionsSubmissionIdAssignment200>(
    getDeleteApiAdminSubmissionsSubmissionIdAssignmentUrl(submissionId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getPatchApiAdminSubmissionsSubmissionIdAssignmentUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/assignment`;
};

export const patchApiAdminSubmissionsSubmissionIdAssignment = async (
  submissionId: string,
  patchApiAdminSubmissionsSubmissionIdAssignmentBody: PatchApiAdminSubmissionsSubmissionIdAssignmentBody,
  options?: RequestInit,
): Promise<PatchApiAdminSubmissionsSubmissionIdAssignment200> => {
  return apiClient<PatchApiAdminSubmissionsSubmissionIdAssignment200>(
    getPatchApiAdminSubmissionsSubmissionIdAssignmentUrl(submissionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(patchApiAdminSubmissionsSubmissionIdAssignmentBody),
    },
  );
};

export const getPostApiAdminSubmissionsSubmissionIdAcceptUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/accept`;
};

export const postApiAdminSubmissionsSubmissionIdAccept = async (
  submissionId: string,
  postApiAdminSubmissionsSubmissionIdAcceptBody: PostApiAdminSubmissionsSubmissionIdAcceptBody,
  options?: RequestInit,
): Promise<PostApiAdminSubmissionsSubmissionIdAccept200> => {
  return apiClient<PostApiAdminSubmissionsSubmissionIdAccept200>(
    getPostApiAdminSubmissionsSubmissionIdAcceptUrl(submissionId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiAdminSubmissionsSubmissionIdAcceptBody),
    },
  );
};

export const getPostApiAdminSubmissionsSubmissionIdDeclineUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/decline`;
};

export const postApiAdminSubmissionsSubmissionIdDecline = async (
  submissionId: string,
  postApiAdminSubmissionsSubmissionIdDeclineBody: PostApiAdminSubmissionsSubmissionIdDeclineBody,
  options?: RequestInit,
): Promise<PostApiAdminSubmissionsSubmissionIdDecline200> => {
  return apiClient<PostApiAdminSubmissionsSubmissionIdDecline200>(
    getPostApiAdminSubmissionsSubmissionIdDeclineUrl(submissionId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiAdminSubmissionsSubmissionIdDeclineBody),
    },
  );
};

export const getPostApiPublicSubmissionsUrl = () => {
  return `/api/public/submissions`;
};

export const postApiPublicSubmissions = async (
  postApiPublicSubmissionsBody: PostApiPublicSubmissionsBody,
  options?: RequestInit,
): Promise<PostApiPublicSubmissions200> => {
  return apiClient<PostApiPublicSubmissions200>(
    getPostApiPublicSubmissionsUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiPublicSubmissionsBody),
    },
  );
};

export const getPostApiPublicSubmissionsDeletionReceiptsVerifyUrl = () => {
  return `/api/public/submissions/deletion-receipts/verify`;
};

export const postApiPublicSubmissionsDeletionReceiptsVerify = async (
  postApiPublicSubmissionsDeletionReceiptsVerifyBody: PostApiPublicSubmissionsDeletionReceiptsVerifyBody,
  options?: RequestInit,
): Promise<PostApiPublicSubmissionsDeletionReceiptsVerify200> => {
  return apiClient<PostApiPublicSubmissionsDeletionReceiptsVerify200>(
    getPostApiPublicSubmissionsDeletionReceiptsVerifyUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiPublicSubmissionsDeletionReceiptsVerifyBody),
    },
  );
};

export const getGetApiPublicSubmissionsDeletionTokenStatusUrl = (
  deletionToken: string,
) => {
  return `/api/public/submissions/${deletionToken}/status`;
};

export const getApiPublicSubmissionsDeletionTokenStatus = async (
  deletionToken: string,
  options?: RequestInit,
): Promise<GetApiPublicSubmissionsDeletionTokenStatus200> => {
  return apiClient<GetApiPublicSubmissionsDeletionTokenStatus200>(
    getGetApiPublicSubmissionsDeletionTokenStatusUrl(deletionToken),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPublicSubmissionsDeletionTokenDownloadUrl = (
  deletionToken: string,
) => {
  return `/api/public/submissions/${deletionToken}/download`;
};

export const getApiPublicSubmissionsDeletionTokenDownload = async (
  deletionToken: string,
  options?: RequestInit,
): Promise<GetApiPublicSubmissionsDeletionTokenDownload200> => {
  return apiClient<GetApiPublicSubmissionsDeletionTokenDownload200>(
    getGetApiPublicSubmissionsDeletionTokenDownloadUrl(deletionToken),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDeleteApiPublicSubmissionsDeletionTokenUrl = (
  deletionToken: string,
) => {
  return `/api/public/submissions/${deletionToken}`;
};

export const deleteApiPublicSubmissionsDeletionToken = async (
  deletionToken: string,
  options?: RequestInit,
): Promise<DeleteApiPublicSubmissionsDeletionToken200> => {
  return apiClient<DeleteApiPublicSubmissionsDeletionToken200>(
    getDeleteApiPublicSubmissionsDeletionTokenUrl(deletionToken),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getGetApiAdminTestUrl = () => {
  return `/api/admin/test`;
};

export const getApiAdminTest = async (
  options?: RequestInit,
): Promise<unknown> => {
  return apiClient<unknown>(getGetApiAdminTestUrl(), {
    ...options,
    method: "GET",
  });
};
