/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * rg-dez-backend
 * OpenAPI spec version: 0.0.0
 */
import { apiClient } from '../lib/apiClient';
export type Def0Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Bad request, input malformed.
 */
export interface Def0 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def0Internal;
}

export type Def1Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Unauthorized
 */
export interface Def1 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def1Internal;
}

export type Def2Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Forbidden
 */
export interface Def2 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def2Internal;
}

export type Def3Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Not found
 */
export interface Def3 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def3Internal;
}

export type Def4Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Method not allowed
 */
export interface Def4 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def4Internal;
}

export type Def5Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Internal server error
 */
export interface Def5 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def5Internal;
}

export type GetApiAdminAuthVerify200AccessTokenRealmAccess = {
  roles: string[];
};

export type GetApiAdminAuthVerify200AccessTokenResourceAccess = {[key: string]: {
  roles: string[];
}};

export type GetApiAdminAuthVerify200AccessToken = {
  scope?: string;
  client_id?: string;
  username?: string;
  token_type?: string;
  exp?: number;
  iat?: number;
  nbf?: number;
  sub?: string;
  aud?: string | string[];
  iss?: string;
  jti?: string;
  realm_access?: GetApiAdminAuthVerify200AccessTokenRealmAccess;
  resource_access?: GetApiAdminAuthVerify200AccessTokenResourceAccess;
  name?: string;
  given_name?: string;
  family_name?: string;
  email_verified?: boolean;
  preferred_username?: string;
  email?: string;
  [key: string]: unknown;
 };

export type GetApiAdminAuthVerify200 = {
  accessToken: GetApiAdminAuthVerify200AccessToken;
};

export const getGetApiAdminAuthVerifyUrl = () => {


  

  return `/api/admin/auth/verify`
}

export const getApiAdminAuthVerify = async ( options?: RequestInit): Promise<GetApiAdminAuthVerify200> => {
  
  return apiClient<GetApiAdminAuthVerify200>(getGetApiAdminAuthVerifyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


export const getGetApiAdminTestUrl = () => {


  

  return `/api/admin/test`
}

export const getApiAdminTest = async ( options?: RequestInit): Promise<unknown> => {
  
  return apiClient<unknown>(getGetApiAdminTestUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
