/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * rg-dez-backend
 * OpenAPI spec version: 0.2.0
 */
import { apiClient } from "../lib/apiClient";
export type Def0Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Bad request, input malformed.
 */
export interface Def0 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def0Internal;
}

export type Def1Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Unauthorized
 */
export interface Def1 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def1Internal;
}

export type Def2Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Forbidden
 */
export interface Def2 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def2Internal;
}

export type Def3Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Not found
 */
export interface Def3 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def3Internal;
}

export type Def4Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Method not allowed
 */
export interface Def4 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def4Internal;
}

export type Def5Internal = {
  stack?: string;
  cause?: string;
};

/**
 * Internal server error
 */
export interface Def5 {
  status: string;
  message: string;
  payload?: unknown;
  internal?: Def5Internal;
}

export type GetApiAdminAuthVerify200AccessTokenRealmAccess = {
  roles: string[];
};

export type GetApiAdminAuthVerify200AccessTokenResourceAccess = {
  [key: string]: {
    roles: string[];
  };
};

export type GetApiAdminAuthVerify200AccessToken = {
  scope?: string;
  client_id?: string;
  username?: string;
  token_type?: string;
  exp?: number;
  iat?: number;
  nbf?: number;
  sub?: string;
  aud?: string | string[];
  iss?: string;
  jti?: string;
  realm_access?: GetApiAdminAuthVerify200AccessTokenRealmAccess;
  resource_access?: GetApiAdminAuthVerify200AccessTokenResourceAccess;
  name?: string;
  given_name?: string;
  family_name?: string;
  email_verified?: boolean;
  preferred_username?: string;
  email?: string;
  [key: string]: unknown;
};

export type GetApiAdminAuthVerify200 = {
  accessToken: GetApiAdminAuthVerify200AccessToken;
};

export type GetApiAdminConfig200ConfigsItem = {
  versionName: string;
  calculationConfig: string;
  subsidies: string;
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiAdminConfig200 = {
  configs: GetApiAdminConfig200ConfigsItem[];
};

export type PostApiAdminConfigBody = {
  /** @minLength 1 */
  versionName: string;
  calculationConfig: string;
  subsidies: string;
};

export type PostApiAdminConfig200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string;
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiAdminConfigVersionName200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string;
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type DeleteApiAdminConfigVersionName200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string;
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiPublicConfigActive200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string;
  publishedAt: unknown;
};

export type PatchApiAdminConfigVersionNameActivate200 = {
  versionName: string;
  calculationConfig: string;
  subsidies: string;
  isActive: boolean;
  createdAt: unknown;
  publishedAt: unknown;
};

export type GetApiAdminSubmissionsParams = {
  managerId?: string;
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  status?: (typeof GetApiAdminSubmissionsStatus)[keyof typeof GetApiAdminSubmissionsStatus];
  sortBy?: (typeof GetApiAdminSubmissionsSortBy)[keyof typeof GetApiAdminSubmissionsSortBy];
};

export const GetApiAdminSubmissionsStatus = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export const GetApiAdminSubmissionsSortBy = {
  status: "status",
  submitted: "submitted",
} as const;
export const GetApiAdminSubmissions200DataItemSubmissionsItemStatus = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export type GetApiAdminSubmissions200DataItemSubmissionsItem = {
  id: string;
  status: (typeof GetApiAdminSubmissions200DataItemSubmissionsItemStatus)[keyof typeof GetApiAdminSubmissions200DataItemSubmissionsItemStatus];
  assignedToId: string | null;
  createdAt: string;
};

export type GetApiAdminSubmissions200DataItem = {
  buildingId: string;
  address: string;
  longitude: number;
  latitude: number;
  submissionCount: number;
  submissions: GetApiAdminSubmissions200DataItemSubmissionsItem[];
};

export type GetApiAdminSubmissions200 = {
  data: GetApiAdminSubmissions200DataItem[];
  total: number;
};

export const GetApiAdminSubmissionsSubmissionId200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export type GetApiAdminSubmissionsSubmissionId200AssignedTo = {
  id: string;
  email: string;
  given_name: string | null;
  family_name: string | null;
} | null;

export type GetApiAdminSubmissionsSubmissionId200NgsiData = {
  [key: string]: unknown;
};

export type GetApiAdminSubmissionsSubmissionId200Raw = {
  [key: string]: unknown;
};

export type GetApiAdminSubmissionsSubmissionId200UsedConfig = {
  id: string;
  versionName: string;
};

export const GetApiAdminSubmissionsSubmissionId200HistoryItemFrom = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export const GetApiAdminSubmissionsSubmissionId200HistoryItemTo = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export type GetApiAdminSubmissionsSubmissionId200HistoryItemBy = {
  id: string;
  email: string;
  given_name: string | null;
  family_name: string | null;
};

export type GetApiAdminSubmissionsSubmissionId200HistoryItem = {
  id: string;
  from: (typeof GetApiAdminSubmissionsSubmissionId200HistoryItemFrom)[keyof typeof GetApiAdminSubmissionsSubmissionId200HistoryItemFrom];
  to: (typeof GetApiAdminSubmissionsSubmissionId200HistoryItemTo)[keyof typeof GetApiAdminSubmissionsSubmissionId200HistoryItemTo];
  by: GetApiAdminSubmissionsSubmissionId200HistoryItemBy;
  createdAt: string;
};

export type GetApiAdminSubmissionsSubmissionId200 = {
  id: string;
  status: (typeof GetApiAdminSubmissionsSubmissionId200Status)[keyof typeof GetApiAdminSubmissionsSubmissionId200Status];
  buildingId: string;
  address: string;
  longitude: number;
  latitude: number;
  otherSubmissionIds: string[];
  assignedTo: GetApiAdminSubmissionsSubmissionId200AssignedTo;
  assignedAt: string | null;
  ngsiData: GetApiAdminSubmissionsSubmissionId200NgsiData;
  raw: GetApiAdminSubmissionsSubmissionId200Raw;
  usedConfig: GetApiAdminSubmissionsSubmissionId200UsedConfig;
  history: GetApiAdminSubmissionsSubmissionId200HistoryItem[];
  createdAt: string;
  updatedAt: string;
};

export type DeleteApiAdminSubmissionsSubmissionId200 = {
  id: string;
};

export const DeleteApiAdminSubmissionsSubmissionIdAssignment200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export type DeleteApiAdminSubmissionsSubmissionIdAssignment200 = {
  id: string;
  status: (typeof DeleteApiAdminSubmissionsSubmissionIdAssignment200Status)[keyof typeof DeleteApiAdminSubmissionsSubmissionIdAssignment200Status];
  assignedToId: string | null;
  assignedAt: string | null;
};

export type PatchApiAdminSubmissionsSubmissionIdAssignmentBody = {
  userId?: string;
};

export const PatchApiAdminSubmissionsSubmissionIdAssignment200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export type PatchApiAdminSubmissionsSubmissionIdAssignment200 = {
  id: string;
  status: (typeof PatchApiAdminSubmissionsSubmissionIdAssignment200Status)[keyof typeof PatchApiAdminSubmissionsSubmissionIdAssignment200Status];
  assignedToId: string | null;
  assignedAt: string | null;
};

export const PostApiAdminSubmissionsSubmissionIdAccept200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export type PostApiAdminSubmissionsSubmissionIdAccept200 = {
  id: string;
  status: (typeof PostApiAdminSubmissionsSubmissionIdAccept200Status)[keyof typeof PostApiAdminSubmissionsSubmissionIdAccept200Status];
  assignedToId: string | null;
  assignedAt: string | null;
};

export const PostApiAdminSubmissionsSubmissionIdDecline200Status = {
  NEW: "NEW",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
} as const;
export type PostApiAdminSubmissionsSubmissionIdDecline200 = {
  id: string;
  status: (typeof PostApiAdminSubmissionsSubmissionIdDecline200Status)[keyof typeof PostApiAdminSubmissionsSubmissionIdDecline200Status];
  assignedToId: string | null;
  assignedAt: string | null;
};

export type PostApiPublicSubmissionsBody = {
  input: unknown;
  configName?: string;
  buildingId: string;
  address: string;
  longitude: number;
  latitude: number;
};

export type PostApiPublicSubmissions200NgsiData = { [key: string]: unknown };

export type PostApiPublicSubmissions200Raw = { [key: string]: unknown };

export type PostApiPublicSubmissions200 = {
  id: string;
  ngsiData: PostApiPublicSubmissions200NgsiData;
  raw: PostApiPublicSubmissions200Raw;
  deletionLink: string;
};

export type GetApiPublicSubmissionsDeletionTokenDelete200 = {
  success: boolean;
};

export const getGetApiAdminAuthVerifyUrl = () => {
  return `/api/admin/auth/verify`;
};

export const getApiAdminAuthVerify = async (
  options?: RequestInit,
): Promise<GetApiAdminAuthVerify200> => {
  return apiClient<GetApiAdminAuthVerify200>(getGetApiAdminAuthVerifyUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetApiAdminConfigUrl = () => {
  return `/api/admin/config`;
};

export const getApiAdminConfig = async (
  options?: RequestInit,
): Promise<GetApiAdminConfig200> => {
  return apiClient<GetApiAdminConfig200>(getGetApiAdminConfigUrl(), {
    ...options,
    method: "GET",
  });
};

export const getPostApiAdminConfigUrl = () => {
  return `/api/admin/config`;
};

export const postApiAdminConfig = async (
  postApiAdminConfigBody: PostApiAdminConfigBody,
  options?: RequestInit,
): Promise<PostApiAdminConfig200> => {
  return apiClient<PostApiAdminConfig200>(getPostApiAdminConfigUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiAdminConfigBody),
  });
};

export const getGetApiAdminConfigVersionNameUrl = (versionName: string) => {
  return `/api/admin/config/${versionName}`;
};

export const getApiAdminConfigVersionName = async (
  versionName: string,
  options?: RequestInit,
): Promise<GetApiAdminConfigVersionName200> => {
  return apiClient<GetApiAdminConfigVersionName200>(
    getGetApiAdminConfigVersionNameUrl(versionName),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDeleteApiAdminConfigVersionNameUrl = (versionName: string) => {
  return `/api/admin/config/${versionName}`;
};

export const deleteApiAdminConfigVersionName = async (
  versionName: string,
  options?: RequestInit,
): Promise<DeleteApiAdminConfigVersionName200> => {
  return apiClient<DeleteApiAdminConfigVersionName200>(
    getDeleteApiAdminConfigVersionNameUrl(versionName),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getGetApiPublicConfigActiveUrl = () => {
  return `/api/public/config/active`;
};

export const getApiPublicConfigActive = async (
  options?: RequestInit,
): Promise<GetApiPublicConfigActive200> => {
  return apiClient<GetApiPublicConfigActive200>(
    getGetApiPublicConfigActiveUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getPatchApiAdminConfigVersionNameActivateUrl = (
  versionName: string,
) => {
  return `/api/admin/config/${versionName}/activate`;
};

export const patchApiAdminConfigVersionNameActivate = async (
  versionName: string,
  options?: RequestInit,
): Promise<PatchApiAdminConfigVersionNameActivate200> => {
  return apiClient<PatchApiAdminConfigVersionNameActivate200>(
    getPatchApiAdminConfigVersionNameActivateUrl(versionName),
    {
      ...options,
      method: "PATCH",
    },
  );
};

export const getGetApiAdminSubmissionsUrl = (
  params?: GetApiAdminSubmissionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/submissions?${stringifiedParams}`
    : `/api/admin/submissions`;
};

export const getApiAdminSubmissions = async (
  params?: GetApiAdminSubmissionsParams,
  options?: RequestInit,
): Promise<GetApiAdminSubmissions200> => {
  return apiClient<GetApiAdminSubmissions200>(
    getGetApiAdminSubmissionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiAdminSubmissionsSubmissionIdUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}`;
};

export const getApiAdminSubmissionsSubmissionId = async (
  submissionId: string,
  options?: RequestInit,
): Promise<GetApiAdminSubmissionsSubmissionId200> => {
  return apiClient<GetApiAdminSubmissionsSubmissionId200>(
    getGetApiAdminSubmissionsSubmissionIdUrl(submissionId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDeleteApiAdminSubmissionsSubmissionIdUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}`;
};

export const deleteApiAdminSubmissionsSubmissionId = async (
  submissionId: string,
  options?: RequestInit,
): Promise<DeleteApiAdminSubmissionsSubmissionId200> => {
  return apiClient<DeleteApiAdminSubmissionsSubmissionId200>(
    getDeleteApiAdminSubmissionsSubmissionIdUrl(submissionId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteApiAdminSubmissionsSubmissionIdAssignmentUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/assignment`;
};

export const deleteApiAdminSubmissionsSubmissionIdAssignment = async (
  submissionId: string,
  options?: RequestInit,
): Promise<DeleteApiAdminSubmissionsSubmissionIdAssignment200> => {
  return apiClient<DeleteApiAdminSubmissionsSubmissionIdAssignment200>(
    getDeleteApiAdminSubmissionsSubmissionIdAssignmentUrl(submissionId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getPatchApiAdminSubmissionsSubmissionIdAssignmentUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/assignment`;
};

export const patchApiAdminSubmissionsSubmissionIdAssignment = async (
  submissionId: string,
  patchApiAdminSubmissionsSubmissionIdAssignmentBody: PatchApiAdminSubmissionsSubmissionIdAssignmentBody,
  options?: RequestInit,
): Promise<PatchApiAdminSubmissionsSubmissionIdAssignment200> => {
  return apiClient<PatchApiAdminSubmissionsSubmissionIdAssignment200>(
    getPatchApiAdminSubmissionsSubmissionIdAssignmentUrl(submissionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(patchApiAdminSubmissionsSubmissionIdAssignmentBody),
    },
  );
};

export const getPostApiAdminSubmissionsSubmissionIdAcceptUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/accept`;
};

export const postApiAdminSubmissionsSubmissionIdAccept = async (
  submissionId: string,
  options?: RequestInit,
): Promise<PostApiAdminSubmissionsSubmissionIdAccept200> => {
  return apiClient<PostApiAdminSubmissionsSubmissionIdAccept200>(
    getPostApiAdminSubmissionsSubmissionIdAcceptUrl(submissionId),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getPostApiAdminSubmissionsSubmissionIdDeclineUrl = (
  submissionId: string,
) => {
  return `/api/admin/submissions/${submissionId}/decline`;
};

export const postApiAdminSubmissionsSubmissionIdDecline = async (
  submissionId: string,
  options?: RequestInit,
): Promise<PostApiAdminSubmissionsSubmissionIdDecline200> => {
  return apiClient<PostApiAdminSubmissionsSubmissionIdDecline200>(
    getPostApiAdminSubmissionsSubmissionIdDeclineUrl(submissionId),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getPostApiPublicSubmissionsUrl = () => {
  return `/api/public/submissions`;
};

export const postApiPublicSubmissions = async (
  postApiPublicSubmissionsBody: PostApiPublicSubmissionsBody,
  options?: RequestInit,
): Promise<PostApiPublicSubmissions200> => {
  return apiClient<PostApiPublicSubmissions200>(
    getPostApiPublicSubmissionsUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiPublicSubmissionsBody),
    },
  );
};

export const getGetApiPublicSubmissionsDeletionTokenDeleteUrl = (
  deletionToken: string,
) => {
  return `/api/public/submissions/${deletionToken}/delete`;
};

export const getApiPublicSubmissionsDeletionTokenDelete = async (
  deletionToken: string,
  options?: RequestInit,
): Promise<GetApiPublicSubmissionsDeletionTokenDelete200> => {
  return apiClient<GetApiPublicSubmissionsDeletionTokenDelete200>(
    getGetApiPublicSubmissionsDeletionTokenDeleteUrl(deletionToken),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiAdminTestUrl = () => {
  return `/api/admin/test`;
};

export const getApiAdminTest = async (
  options?: RequestInit,
): Promise<unknown> => {
  return apiClient<unknown>(getGetApiAdminTestUrl(), {
    ...options,
    method: "GET",
  });
};
