import {
  BuildingType,
  RoofInsulationType,
  type DETInput,
} from "@csi-foxbyte/regensburg_digitalerenergiezwilling_energycalculationcore";
import { type BuildingRecord } from "./types";

export type BuildingStatus = "neu" | "freigegeben" | "abgelehnt";

// Reusable detInput fragments
const noRoofWindows = {
  area: 0,
  year: null,
  windowType: null,
  uValue: null,
} satisfies DETInput["roofWindows"];

export const mockRecords: BuildingRecord[] = [
  {
    id: "1",
    buildingAddress: "Hauptstraße 15, 10115 Berlin",
    receivedDate: "2026-03-27T10:30:00",
    status: "NEU",
    assignedTo: null,
    assignedAt: null,
    notes: "",
    detInput: {
      general: {
        buildingYear: 1985,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 80,
        livingArea: 140,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2022,
        primaryEnergyCarrier: "electricity",
        heatingSystemType: "air_source_heat_pump_lt_40",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 85,
        year: 1985,
        hasInsulation: true,
        insulationType: RoofInsulationType.BETWEEN_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 16,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 25,
        year: 2021,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.9,
      },
      topFloor: {
        area: 80,
        year: 1985,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 18,
        hasAttic: false,
      },
      outerWall: {
        area: 210,
        year: 2021,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 14,
      },
      bottomFloor: {
        area: 80,
        year: 1985,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 8,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "2",
    buildingAddress: "Alexanderplatz 5, 10178 Berlin",
    receivedDate: "2026-03-24T14:20:00",
    status: "IN_PRUEFUNG",
    assignedTo: "Anna Schmidt",
    assignedAt: new Date("2026-03-24T14:20:00"),
    notes: "Effizienzklasse muss noch verifiziert werden.",
    detInput: {
      general: {
        buildingYear: 1960,
        numberOfStories: 5,
        buildingHeight: 16.0,
        buildingBaseArea: 185,
        livingArea: 850,
        type: BuildingType.MULTI_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2015,
        primaryEnergyCarrier: "natural_gas",
        heatingSystemType: "condensing_boiler_70_55",
        heatingSurfaceType: "free_heat_emitter",
      },
      roof: {
        area: 190,
        year: 1960,
        hasInsulation: false,
        insulationType: null,
        constructionType: "solid_construction",
        insulationThickness: null,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 120,
        year: 2015,
        windowType: "wooden_window_double_glazing",
        uValue: 2.7,
      },
      topFloor: {
        area: 185,
        year: 1960,
        isAtticHeated: false,
        topFloorType: "solid_ceiling",
        hasInsulation: false,
        insulationThickness: null,
        hasAttic: true,
      },
      outerWall: {
        area: 520,
        year: 1960,
        hasInsulation: false,
        constructionType: "brick_wall",
        insulationThickness: null,
      },
      bottomFloor: {
        area: 185,
        year: 1960,
        isHeated: false,
        hasInsulation: false,
        constructionType: "reinforced_concrete_ceiling",
        insulationThickness: null,
        hasBasement: true,
        isBasementHeated: false,
      },
    },
  },
  {
    id: "3",
    buildingAddress: "Berliner Allee 42, 10115 Berlin",
    receivedDate: "2026-03-26T09:15:00",
    status: "NEU",
    assignedTo: null,
    assignedAt: null,
    notes: "",
  },
  {
    id: "4",
    buildingAddress: "Friedrichstraße 123, 10117 Berlin",
    receivedDate: "2026-03-23T11:45:00",
    status: "FREIGEGEBEN",
    assignedTo: "Michael Weber",
    assignedAt: new Date("2026-03-23T11:45:00"),
    notes: "Alle Angaben korrekt und plausibel. Freigegeben für Export.",
    detInput: {
      general: {
        buildingYear: 2000,
        numberOfStories: 2,
        buildingHeight: 7.5,
        buildingBaseArea: 100,
        livingArea: 180,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2020,
        primaryEnergyCarrier: "natural_gas",
        heatingSystemType: "improved_condensing_boiler_55_45",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 110,
        year: 2020,
        hasInsulation: true,
        insulationType: RoofInsulationType.ABOVE_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 20,
      },
      roofWindows: {
        area: 3.0,
        year: 2020,
        windowType: "plastic_window_insulated_glazing",
        uValue: 1.0,
      },
      exteriorWallWindows: {
        area: 32,
        year: 2020,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.8,
      },
      topFloor: {
        area: 100,
        year: 2020,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 24,
        hasAttic: false,
      },
      outerWall: {
        area: 260,
        year: 2020,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 16,
      },
      bottomFloor: {
        area: 100,
        year: 2000,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 12,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "5",
    buildingAddress: "Schillerstraße 89, 10625 Berlin",
    receivedDate: "2026-03-22T16:30:00",
    status: "UNPLAUSIBEL",
    assignedTo: "Anna Schmidt",
    assignedAt: new Date("2026-03-22T16:30:00"),
    notes:
      "Widersprüchliche Angaben zum Baujahr und Energiesystem. Nicht plausibel.",
    detInput: {
      general: {
        buildingYear: 2023,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 80,
        livingArea: 140,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2025,
        primaryEnergyCarrier: "heating_oil_light",
        heatingSystemType: "standard_boiler_70_55",
        heatingSurfaceType: "free_heat_emitter",
      },
      roof: {
        area: 85,
        year: 2023,
        hasInsulation: false,
        insulationType: null,
        constructionType: "wood_construction",
        insulationThickness: null,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 25,
        year: 1980,
        windowType: "wooden_window_single_glazing",
        uValue: 5.2,
      },
      topFloor: {
        area: 80,
        year: 2023,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: false,
        insulationThickness: null,
        hasAttic: false,
      },
      outerWall: {
        area: 210,
        year: 2023,
        hasInsulation: false,
        constructionType: "other_wall",
        insulationThickness: null,
      },
      bottomFloor: {
        area: 80,
        year: 2023,
        isHeated: false,
        hasInsulation: false,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: null,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "6",
    buildingAddress: "Kurfürstendamm 88, 10709 Berlin",
    receivedDate: "2026-03-26T08:00:00",
    status: "NEU",
    assignedTo: null,
    assignedAt: null,
    notes: "",
    detInput: {
      general: {
        buildingYear: 1955,
        numberOfStories: 4,
        buildingHeight: 13.0,
        buildingBaseArea: 165,
        livingArea: 620,
        type: BuildingType.MULTI_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2021,
        primaryEnergyCarrier: "wood_pellets",
        heatingSystemType: "standard_boiler_70_55",
        heatingSurfaceType: "free_heat_emitter",
      },
      roof: {
        area: 170,
        year: 2021,
        hasInsulation: true,
        insulationType: RoofInsulationType.ABOVE_RAFTER,
        constructionType: "solid_construction",
        insulationThickness: 14,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 90,
        year: 2021,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.9,
      },
      topFloor: {
        area: 165,
        year: 2021,
        isAtticHeated: false,
        topFloorType: "solid_ceiling",
        hasInsulation: true,
        insulationThickness: 16,
        hasAttic: true,
      },
      outerWall: {
        area: 480,
        year: 2021,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 12,
      },
      bottomFloor: {
        area: 165,
        year: 1955,
        isHeated: false,
        hasInsulation: false,
        constructionType: "reinforced_concrete_ceiling",
        insulationThickness: null,
        hasBasement: true,
        isBasementHeated: false,
      },
    },
  },
  {
    id: "7",
    buildingAddress: "Kastanienallee 34, 10435 Berlin",
    receivedDate: "2026-03-27T07:45:00",
    status: "NEU",
    assignedTo: null,
    assignedAt: null,
    notes: "",
    detInput: {
      general: {
        buildingYear: 1995,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 90,
        livingArea: 165,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2023,
        primaryEnergyCarrier: "electricity",
        heatingSystemType: "air_source_heat_pump_lt_40",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 95,
        year: 2023,
        hasInsulation: true,
        insulationType: RoofInsulationType.BETWEEN_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 20,
      },
      roofWindows: {
        area: 1.8,
        year: 2023,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.9,
      },
      exteriorWallWindows: {
        area: 28,
        year: 2023,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.8,
      },
      topFloor: {
        area: 90,
        year: 2023,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 22,
        hasAttic: false,
      },
      outerWall: {
        area: 240,
        year: 1995,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 10,
      },
      bottomFloor: {
        area: 90,
        year: 1995,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 10,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "8",
    buildingAddress: "Sonnenallee 245, 12057 Berlin",
    receivedDate: "2026-03-24T09:30:00",
    status: "FREIGEGEBEN",
    assignedTo: "Max Müller",
    assignedAt: new Date("2026-03-24T09:30:00"),
    notes: "Alle Unterlagen vollständig und plausibel.",
    detInput: {
      general: {
        buildingYear: 1988,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 85,
        livingArea: 155,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2021,
        primaryEnergyCarrier: "electricity",
        heatingSystemType: "air_source_heat_pump_lt_40",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 90,
        year: 2021,
        hasInsulation: true,
        insulationType: RoofInsulationType.BETWEEN_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 18,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 26,
        year: 2021,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.9,
      },
      topFloor: {
        area: 85,
        year: 2021,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 20,
        hasAttic: false,
      },
      outerWall: {
        area: 225,
        year: 1988,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 12,
      },
      bottomFloor: {
        area: 85,
        year: 1988,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 8,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "8",
    buildingAddress: "Karl-Marx-Allee 90, 10243 Berlin",
    receivedDate: "2026-03-22T13:45:00",
    status: "FREIGEGEBEN",
    assignedTo: "Michael Weber",
    assignedAt: new Date("2026-03-22T13:45:00"),
    notes: "Denkmalschutzauflagen beachtet. Freigegeben.",
    detInput: {
      general: {
        buildingYear: 1952,
        numberOfStories: 6,
        buildingHeight: 19.0,
        buildingBaseArea: 200,
        livingArea: 1100,
        type: BuildingType.MULTI_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2014,
        primaryEnergyCarrier: "district_heating",
        heatingSystemType: "district_heating_all_temperatures",
        heatingSurfaceType: "free_heat_emitter",
      },
      roof: {
        area: 210,
        year: 1952,
        hasInsulation: false,
        insulationType: null,
        constructionType: "solid_construction",
        insulationThickness: null,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 160,
        year: 2014,
        windowType: "wooden_window_double_glazing",
        uValue: 2.8,
      },
      topFloor: {
        area: 200,
        year: 1952,
        isAtticHeated: false,
        topFloorType: "solid_ceiling",
        hasInsulation: false,
        insulationThickness: null,
        hasAttic: true,
      },
      outerWall: {
        area: 640,
        year: 2014,
        hasInsulation: true,
        constructionType: "brick_wall",
        insulationThickness: 6,
      },
      bottomFloor: {
        area: 200,
        year: 1952,
        isHeated: false,
        hasInsulation: false,
        constructionType: "reinforced_concrete_ceiling",
        insulationThickness: null,
        hasBasement: true,
        isBasementHeated: false,
      },
    },
  },
  {
    id: "9",
    buildingAddress: "Spandauer Damm 45, 14059 Berlin",
    receivedDate: "2026-03-27T09:00:00",
    status: "NEU",
    assignedTo: null,
    assignedAt: null,
    notes: "",
    detInput: {
      general: {
        buildingYear: 1992,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 105,
        livingArea: 190,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2020,
        primaryEnergyCarrier: "wood_pellets",
        heatingSystemType: "standard_boiler_70_55",
        heatingSurfaceType: "free_heat_emitter",
      },
      roof: {
        area: 115,
        year: 2020,
        hasInsulation: true,
        insulationType: RoofInsulationType.BETWEEN_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 16,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 32,
        year: 2020,
        windowType: "plastic_window_insulated_glazing",
        uValue: 1.0,
      },
      topFloor: {
        area: 105,
        year: 2020,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 18,
        hasAttic: false,
      },
      outerWall: {
        area: 275,
        year: 1992,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 10,
      },
      bottomFloor: {
        area: 105,
        year: 1992,
        isHeated: false,
        hasInsulation: false,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: null,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "10",
    buildingAddress: "Bornholmer Straße 78, 10439 Berlin",
    receivedDate: "2026-03-24T15:00:00",
    status: "FREIGEGEBEN",
    assignedTo: "Anna Schmidt",
    assignedAt: new Date("2026-03-24T15:00:00"),
    notes: "Alle Angaben geprüft und freigegeben.",
    detInput: {
      general: {
        buildingYear: 1990,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 88,
        livingArea: 160,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2019,
        primaryEnergyCarrier: "electricity",
        heatingSystemType: "air_source_heat_pump_55_45",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 92,
        year: 2019,
        hasInsulation: true,
        insulationType: RoofInsulationType.ABOVE_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 18,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 28,
        year: 2019,
        windowType: "plastic_window_insulated_glazing",
        uValue: 1.0,
      },
      topFloor: {
        area: 88,
        year: 2019,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 20,
        hasAttic: false,
      },
      outerWall: {
        area: 230,
        year: 1990,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 10,
      },
      bottomFloor: {
        area: 88,
        year: 1990,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 8,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "11",
    buildingAddress: "Adlergestell 298, 12489 Berlin",
    receivedDate: "2026-03-22T10:00:00",
    status: "FREIGEGEBEN",
    assignedTo: "Max Müller",
    assignedAt: new Date("2026-03-22T10:00:00"),
    notes: "Neubau mit aktueller Dämmung. Freigegeben.",
    detInput: {
      general: {
        buildingYear: 2023,
        numberOfStories: 2,
        buildingHeight: 7.5,
        buildingBaseArea: 95,
        livingArea: 170,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2023,
        primaryEnergyCarrier: "electricity",
        heatingSystemType: "air_source_heat_pump_lt_40",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 100,
        year: 2023,
        hasInsulation: true,
        insulationType: RoofInsulationType.ABOVE_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 26,
      },
      roofWindows: {
        area: 4.0,
        year: 2023,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.8,
      },
      exteriorWallWindows: {
        area: 34,
        year: 2023,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.7,
      },
      topFloor: {
        area: 95,
        year: 2023,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 28,
        hasAttic: false,
      },
      outerWall: {
        area: 255,
        year: 2023,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 18,
      },
      bottomFloor: {
        area: 95,
        year: 2023,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 14,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "12a",
    buildingAddress: "Ludwigstraße 25, 93047 Regensburg",
    receivedDate: "2026-03-20T09:30:00",
    status: "UNPLAUSIBEL",
    assignedTo: "Michael Weber",
    assignedAt: new Date("2026-03-23T10:00:00"),
    notes: "Automatisch abgelehnt, da Einreichung B freigegeben wurde.",
    variantGroup: "group-12",
    variantLabel: "Einreichung A",
    rejectedDueToApprovalOf: "12b",
    rejectedDueToApprovalOfLabel: "Einreichung B",
    detInput: {
      general: {
        buildingYear: 1985,
        numberOfStories: 3,
        buildingHeight: 10.0,
        buildingBaseArea: 120,
        livingArea: 320,
        type: BuildingType.MULTI_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2010,
        primaryEnergyCarrier: "natural_gas",
        heatingSystemType: "low_temperature_boiler_oil_gas_70_55",
        heatingSurfaceType: "free_heat_emitter",
      },
      roof: {
        area: 130,
        year: 1985,
        hasInsulation: false,
        insulationType: null,
        constructionType: "solid_construction",
        insulationThickness: null,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 55,
        year: 1985,
        windowType: "wooden_window_double_glazing",
        uValue: 2.8,
      },
      topFloor: {
        area: 120,
        year: 1985,
        isAtticHeated: false,
        topFloorType: "solid_ceiling",
        hasInsulation: false,
        insulationThickness: null,
        hasAttic: true,
      },
      outerWall: {
        area: 380,
        year: 1985,
        hasInsulation: false,
        constructionType: "brick_wall",
        insulationThickness: null,
      },
      bottomFloor: {
        area: 120,
        year: 1985,
        isHeated: false,
        hasInsulation: false,
        constructionType: "reinforced_concrete_ceiling",
        insulationThickness: null,
        hasBasement: true,
        isBasementHeated: false,
      },
    },
  },
  {
    id: "12b",
    buildingAddress: "Ludwigstraße 25, 93047 Regensburg",
    receivedDate: "2026-03-23T11:45:00",
    status: "FREIGEGEBEN",
    assignedTo: "Anna Schmidt",
    assignedAt: new Date("2026-03-23T11:45:00"),
    notes: "Alle Angaben korrekt und plausibel. Freigegeben.",
    variantGroup: "group-12",
    variantLabel: "Einreichung B",
    detInput: {
      general: {
        buildingYear: 1985,
        numberOfStories: 3,
        buildingHeight: 10.0,
        buildingBaseArea: 120,
        livingArea: 320,
        type: BuildingType.MULTI_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2020,
        primaryEnergyCarrier: "district_heating",
        heatingSystemType: "district_heating_all_temperatures",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 130,
        year: 2020,
        hasInsulation: true,
        insulationType: RoofInsulationType.BETWEEN_RAFTER,
        constructionType: "solid_construction",
        insulationThickness: 12,
      },
      roofWindows: noRoofWindows,
      exteriorWallWindows: {
        area: 55,
        year: 2020,
        windowType: "plastic_window_insulated_glazing",
        uValue: 1.2,
      },
      topFloor: {
        area: 120,
        year: 2020,
        isAtticHeated: false,
        topFloorType: "solid_ceiling",
        hasInsulation: true,
        insulationThickness: 14,
        hasAttic: true,
      },
      outerWall: {
        area: 380,
        year: 2020,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 10,
      },
      bottomFloor: {
        area: 120,
        year: 1985,
        isHeated: false,
        hasInsulation: false,
        constructionType: "reinforced_concrete_ceiling",
        insulationThickness: null,
        hasBasement: true,
        isBasementHeated: false,
      },
    },
  },
  {
    id: "13a",
    buildingAddress: "Maximilianstraße 12, 93047 Regensburg",
    receivedDate: "2026-03-25T14:00:00",
    status: "NEU",
    assignedTo: null,
    assignedAt: null,
    notes: "",
    variantGroup: "group-13",
    variantLabel: "Einreichung A",
    detInput: {
      general: {
        buildingYear: 1990,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 80,
        livingArea: 140,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2022,
        primaryEnergyCarrier: "electricity",
        heatingSystemType: "air_source_heat_pump_lt_40",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 92,
        year: 2022,
        hasInsulation: true,
        insulationType: RoofInsulationType.ABOVE_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 22,
      },
      roofWindows: {
        area: 2.5,
        year: 2022,
        windowType: "plastic_window_insulated_glazing",
        uValue: 1.0,
      },
      exteriorWallWindows: {
        area: 26,
        year: 2022,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.9,
      },
      topFloor: {
        area: 80,
        year: 2022,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 22,
        hasAttic: false,
      },
      outerWall: {
        area: 210,
        year: 1990,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 12,
      },
      bottomFloor: {
        area: 80,
        year: 1990,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 10,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
  {
    id: "13b",
    buildingAddress: "Maximilianstraße 12, 93047 Regensburg",
    receivedDate: "2026-03-26T10:30:00",
    status: "NEU",
    assignedTo: null,
    assignedAt: null,
    notes: "",
    variantGroup: "group-13",
    variantLabel: "Einreichung B",
    detInput: {
      general: {
        buildingYear: 1990,
        numberOfStories: 2,
        buildingHeight: 7.0,
        buildingBaseArea: 82,
        livingArea: 145,
        type: BuildingType.SINGLE_FAMILY,
      },
      heat: {
        heatingSystemConstructionYear: 2023,
        primaryEnergyCarrier: "renewable_electricity",
        heatingSystemType: "ground_source_heat_pump_lt_40",
        heatingSurfaceType: "radiant_surface_heating",
      },
      roof: {
        area: 95,
        year: 2023,
        hasInsulation: true,
        insulationType: RoofInsulationType.ABOVE_RAFTER,
        constructionType: "wood_construction",
        insulationThickness: 26,
      },
      roofWindows: {
        area: 3.0,
        year: 2023,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.8,
      },
      exteriorWallWindows: {
        area: 28,
        year: 2023,
        windowType: "plastic_window_insulated_glazing",
        uValue: 0.7,
      },
      topFloor: {
        area: 82,
        year: 2023,
        isAtticHeated: false,
        topFloorType: "wood_beam_ceiling",
        hasInsulation: true,
        insulationThickness: 26,
        hasAttic: false,
      },
      outerWall: {
        area: 215,
        year: 1990,
        hasInsulation: true,
        constructionType: "solid_wall_with_thermal_insulation_composite_system",
        insulationThickness: 16,
      },
      bottomFloor: {
        area: 82,
        year: 1990,
        isHeated: true,
        hasInsulation: true,
        constructionType: "reinforced_concrete_on_ground",
        insulationThickness: 12,
        hasBasement: false,
        isBasementHeated: null,
      },
    },
  },
];
