/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageRouteImport } from './routes/page'
import { Route as MaintenancePageRouteImport } from './routes/maintenance/page'
import { Route as LoginPageRouteImport } from './routes/login/page'
import { Route as DashboardPageRouteImport } from './routes/dashboard/page'
import { Route as ConfigPageRouteImport } from './routes/config/page'
import { Route as RecordIdPageRouteImport } from './routes/record/$id/page'

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancePageRoute = MaintenancePageRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPageRoute = DashboardPageRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigPageRoute = ConfigPageRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIdPageRoute = RecordIdPageRouteImport.update({
  id: '/record/$id/',
  path: '/record/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/config/': typeof ConfigPageRoute
  '/dashboard/': typeof DashboardPageRoute
  '/login/': typeof LoginPageRoute
  '/maintenance/': typeof MaintenancePageRoute
  '/record/$id/': typeof RecordIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/config': typeof ConfigPageRoute
  '/dashboard': typeof DashboardPageRoute
  '/login': typeof LoginPageRoute
  '/maintenance': typeof MaintenancePageRoute
  '/record/$id': typeof RecordIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/config/': typeof ConfigPageRoute
  '/dashboard/': typeof DashboardPageRoute
  '/login/': typeof LoginPageRoute
  '/maintenance/': typeof MaintenancePageRoute
  '/record/$id/': typeof RecordIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config/'
    | '/dashboard/'
    | '/login/'
    | '/maintenance/'
    | '/record/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/dashboard' | '/login' | '/maintenance' | '/record/$id'
  id:
    | '__root__'
    | '/'
    | '/config/'
    | '/dashboard/'
    | '/login/'
    | '/maintenance/'
    | '/record/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  ConfigPageRoute: typeof ConfigPageRoute
  DashboardPageRoute: typeof DashboardPageRoute
  LoginPageRoute: typeof LoginPageRoute
  MaintenancePageRoute: typeof MaintenancePageRoute
  RecordIdPageRoute: typeof RecordIdPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenancePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$id/': {
      id: '/record/$id/'
      path: '/record/$id'
      fullPath: '/record/$id/'
      preLoaderRoute: typeof RecordIdPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  ConfigPageRoute: ConfigPageRoute,
  DashboardPageRoute: DashboardPageRoute,
  LoginPageRoute: LoginPageRoute,
  MaintenancePageRoute: MaintenancePageRoute,
  RecordIdPageRoute: RecordIdPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
