/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelloWorldLayoutRouteImport } from './routes/hello-world/layout'
import { Route as PageRouteImport } from './routes/page'
import { Route as HelloWorldPageRouteImport } from './routes/hello-world/page'

const HelloWorldLayoutRoute = HelloWorldLayoutRouteImport.update({
  id: '/hello-world',
  path: '/hello-world',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloWorldPageRoute = HelloWorldPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelloWorldLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/hello-world': typeof HelloWorldLayoutRouteWithChildren
  '/hello-world/': typeof HelloWorldPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/hello-world': typeof HelloWorldPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/hello-world': typeof HelloWorldLayoutRouteWithChildren
  '/hello-world/': typeof HelloWorldPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hello-world' | '/hello-world/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hello-world'
  id: '__root__' | '/' | '/hello-world' | '/hello-world/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  HelloWorldLayoutRoute: typeof HelloWorldLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello-world': {
      id: '/hello-world'
      path: '/hello-world'
      fullPath: '/hello-world'
      preLoaderRoute: typeof HelloWorldLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello-world/': {
      id: '/hello-world/'
      path: '/'
      fullPath: '/hello-world/'
      preLoaderRoute: typeof HelloWorldPageRouteImport
      parentRoute: typeof HelloWorldLayoutRoute
    }
  }
}

interface HelloWorldLayoutRouteChildren {
  HelloWorldPageRoute: typeof HelloWorldPageRoute
}

const HelloWorldLayoutRouteChildren: HelloWorldLayoutRouteChildren = {
  HelloWorldPageRoute: HelloWorldPageRoute,
}

const HelloWorldLayoutRouteWithChildren =
  HelloWorldLayoutRoute._addFileChildren(HelloWorldLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  HelloWorldLayoutRoute: HelloWorldLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
